
on:
  push:
    branches: [ master ]
jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
    
      ## deploy to production
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'master')
        with:
          host: ec2-52-78-230-80.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          key: admin
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f $(docker container rm -f main-service)
            docker image prune -f -a
            docker run -d --network joinus-network --name main-service -e "spring.cloud.config.uri=http://config-service:8888" -e "spring.rabbitmq.host=rabbitmq" -e "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/" -e "logging.file=/api-logs/users-ws.log" refinedstone/main-service

